Copyright = "2018 - All Rights Reserved"
baseurl = "https://ivanportugal.com/"
canonifyurls = true
googleAnalytics = "UA-69208034-1"
languageCode = "en-us"
paginate = 5
theme = "hugo-cactus-theme"
title = "Ramblings of a Software Developer"
[[menu.main]]
name = "BSearch"
url = "https://bsearch.ivanportugal.com/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Ivan Portugal Blog"
url = "/"
weight = 1
[params]
author = "Ivan Portugal"
authorlocation = "Charlotte, North Carolina"
authorwebsite = "https://ivanportugal.com"
bio = "web tech enthusiast"
cover = "img/IvanSkydiving.jpg"
description = "web tech enthusiast"
githubName = "ivanbportugal"
googleAnalyticsUserID = "UA-69208034-1"
iconFont = "mono-social"
logo = "img/smiley.png"
name = "Ivan Portugal"
socialIconStyle = "circle"
[social]
linkedin = "https://linkedin.com/in/ivanportugal"
