baseurl = "https://ivanportugal.com/"
languageCode = "en-us"
title = "Ramblings of a Software Developer"
theme = "hugo-cactus-theme"
paginate = 5
Copyright = "2018 - All Rights Reserved"
canonifyurls = true
# disqusShortname = "IvanPortugal"
googleAnalytics = "UA-69208034-1"
[params]
    name = "Ivan Portugal"
    bio = "web tech enthusiast"
	description = "web tech enthusiast"
	cover = "img/IvanSkydiving.jpg"
	author = "Ivan Portugal"
	authorlocation = "Charlotte, North Carolina"
	authorwebsite = "https://ivanportugal.com"
	githubName = "ivanbportugal"
	logo = "img/smiley.png"
	googleAnalyticsUserID = "UA-69208034-1"

    iconFont = "mono-social"
    socialIconStyle = "circle"

[[menu.main]]
    name = "Ivan Portugal Blog"
    weight = -120
    identifier = "blog"
    url = "/"

[social]
    linkedin = "https://linkedin.com/in/ivanportugal"